/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lab
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private boolean suma;
    private boolean resta;
    private boolean multi;
    private boolean div;
    private boolean modulo;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        num1 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        resultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jrbsuma = new javax.swing.JRadioButton();
        jrbresta = new javax.swing.JRadioButton();
        jrbmult = new javax.swing.JRadioButton();
        jrbdiv = new javax.swing.JRadioButton();
        jrbmodule = new javax.swing.JRadioButton();
        showres = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero 1");

        jLabel2.setText("Numero 2");

        jLabel3.setText("Resultado");

        buttonGroup1.add(jrbsuma);
        jrbsuma.setText("Suma");
        jrbsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbsumaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbresta);
        jrbresta.setText("Resta");
        jrbresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbrestaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbmult);
        jrbmult.setText("Multiplicación");
        jrbmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmultActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbdiv);
        jrbdiv.setText("Division");
        jrbdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbdivActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbmodule);
        jrbmodule.setText("Modulo");
        jrbmodule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmoduleActionPerformed(evt);
            }
        });

        showres.setText("Resultado");
        showres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showresActionPerformed(evt);
            }
        });

        jLabel4.setText("Division por 0 no aceptada");

        jLabel5.setText("Modulo 0 no aceptado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jrbsuma))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbresta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbmult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbdiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jrbmodule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(showres, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbsuma)
                    .addComponent(jrbresta)
                    .addComponent(jrbmult)
                    .addComponent(jrbdiv)
                    .addComponent(jrbmodule))
                .addGap(18, 18, 18)
                .addComponent(showres, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_num1ActionPerformed

    private void jrbsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbsumaActionPerformed
        setFalse();
        suma=true;
    }//GEN-LAST:event_jrbsumaActionPerformed

    private void jrbrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbrestaActionPerformed
        setFalse();
        resta=true;
    }//GEN-LAST:event_jrbrestaActionPerformed

    private void jrbdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbdivActionPerformed
        setFalse();
        div=true;
    }//GEN-LAST:event_jrbdivActionPerformed

    private void jrbmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmultActionPerformed
        setFalse();
        multi=true;
    }//GEN-LAST:event_jrbmultActionPerformed

    private void jrbmoduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmoduleActionPerformed
        setFalse();
        modulo=true;
    }//GEN-LAST:event_jrbmoduleActionPerformed

    private void showresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showresActionPerformed
        double n1=Double.parseDouble(this.num1.getText());
        double n2=Double.parseDouble(this.num2.getText());
        double result=0;
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        if(suma){
            result=n1+n2;
        }
        if(resta){
            result=n1-n2;
        }
        if(div){
            if(n2!=0){
                result=n1/n2;
            }else{
                jLabel4.setVisible(true);
            }
        }
        if(multi){
            result=n1*n2;
        }
        if(modulo){
            if(n2!=0){
                result=n1%n2;
            }else{
                jLabel5.setVisible(true);
            }
        }
        resultado.setText(""+result);
    }//GEN-LAST:event_showresActionPerformed
    
    private void setFalse(){
        suma=false;
        resta=false;
        div=false;
        multi=false;
        modulo=false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jrbdiv;
    private javax.swing.JRadioButton jrbmodule;
    private javax.swing.JRadioButton jrbmult;
    private javax.swing.JRadioButton jrbresta;
    private javax.swing.JRadioButton jrbsuma;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton showres;
    // End of variables declaration//GEN-END:variables
}
